### ISSUE TITLE
Special behavior of *Big.Int once it is stored in variable/map

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/go-sdk#10]
I lost some time over some behavior of *Bit.Int once it stored in a variable, reader can verify by looking at tx-controller.go:183 and notice how referencing the transfer-amount via a map is commented out in favor of recomputing the amt. Hence amount is needlessly passed to several methods, redundantly. 

Find out the root explanation of *Big.Int in the case of it being stored in a variable and losing ~8 decimal points, take that into account and fix the various spots in tx-controller.go that take amount, basically only `C.setAmount` should be taking `amount`

**Comment by Daniel-VDM** [comment]
Is this still relevant?
