### ISSUE TITLE
One1 address is not propery checked

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/go-sdk#104]
One can check the balance of an invalid `one1...` address and it will return something. We should verify that the length of the account address is correct.

Ex:
```
./hmy.sh balances onedeadbeef --node=https://api.s1.t.hmny.io/

[
  {
    "shard": 0,
    "amount": 0.0000003
  },
  {
    "shard": 1,
    "amount": 2.0000
  },
  {
    "shard": 2,
    "amount": 903.566074606
  },
  {
    "shard": 3,
    "amount": 151.363590425
  }
]
```

**Comment by fxfactorial** [comment]
Validation on address already done, see the address type in cmd

**Comment by Daniel-VDM** [comment]
Need to also add address check for `hmy blockchain current-nonce`

**Comment by janet-harmony** [comment]
@fxfactorial Address is checked for transactions, but not for balance check

```
Args:  cobra.ExactArgs(1),
...
balanceRPCReply, err := rpc.Request(rpc.Method.GetBalance, node, []interface{}{args[0], "latest"})
```

**Comment by fxfactorial** [comment]
I see, I think balances was one of the first commands implemented. Before soph implemented address validation. Let’s use this as opportunity to check address validation on all commands that use one address
