### ISSUE TITLE
Allow all passphrase logic to have an option to specify from file. 

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/go-sdk#119]
The old wallet in the main repo allows passphrase to be passed in from a file, we need to also support this. 

We should allow the user to specify passphrase from a file as an additional option.

**Comment by fxfactorial** [comment]
Actually I was thinking about this and we could add —file as a global flag to mean where —file make sense , for example, we could accept json file of an array of values intended for sequential transfers. This would make it much easier to play with say js made tools and other ecosystem tools.
