### ISSUE TITLE
Weird account balance for a testnet address breaks ./hmy balances

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/go-sdk#134]
I'm not sure exactly how - but one of my test case accounts ended up having the hex balance of `0x14` on shard 2 on the testnet `https://api.s2.b.hmny.io`

First off, hmy version (built within the last 30 minutes based on the latest go-sdk master):
```
$ ./hmy version
Harmony (C) 2020. hmy, version v255-cfaf9ff (sebastianjohnsson@harmony.one 2020-02-07T16:43:48+0700)
```

When I run the following balance check hmy panics:
```
$ ./hmy balances one1tcgayvuhq55gp7qasqn77kshfykn9kqx0akzt7 --node https://api.s0.b.hmny.io

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x41613e0]

goroutine 1 [running]:
math/big.(*Int).Mul(0xc00043de40, 0x0, 0xc0000b6240, 0xc000593978)
	~/.gvm/gos/go1.13.7/src/math/big/int.go:168 +0xd0
github.com/harmony-one/harmony/numeric.NewDecFromBigIntWithPrec(0x0, 0x0, 0x2)
	~/Programming/Golang/pkg/mod/github.com/harmony-one/harmony@v1.3.0/numeric/decimal.go:102 +0x70
github.com/harmony-one/harmony/numeric.NewDecFromBigInt(...)
	~/Programming/Golang/pkg/mod/github.com/harmony-one/harmony@v1.3.0/numeric/decimal.go:95
github.com/harmony-one/go-sdk/pkg/common.NewDecFromHex(0xc000493d0c, 0x4, 0x48120ab)
	~/Programming/Golang/src/github.com/harmony-one/go-sdk/pkg/common/numeric.go:67 +0x1ab
github.com/harmony-one/go-sdk/pkg/sharding.CheckAllShards(0x7ffeefbff0d9, 0x18, 0x7ffeefbff0a7, 0x2a, 0x0, 0xc000331c90, 0xc000331c20, 0x4557554, 0xc000363180)
	~/Programming/Golang/src/github.com/harmony-one/go-sdk/pkg/sharding/structure.go:60 +0x4c0
github.com/harmony-one/go-sdk/cmd/subcommands.init.0.func1(0xc0002f2280, 0xc00036a750, 0x1, 0x3, 0x0, 0x0)
	~/Programming/Golang/src/github.com/harmony-one/go-sdk/cmd/subcommands/balance.go:48 +0x6a6
github.com/spf13/cobra.(*Command).execute(0xc0002f2280, 0xc00036a630, 0x3, 0x3, 0xc0002f2280, 0xc00036a630)
	~/Programming/Golang/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x4f79440, 0x1, 0xffffffffffffffff, 0x7)
	~/Programming/Golang/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	~/Programming/Golang/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
	~/Programming/Golang/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:112 +0x4d
main.main()
	~/Programming/Golang/src/github.com/harmony-one/go-sdk/cmd/main.go:38 +0x163
```

If you run the command with `./hmy balances one1tcgayvuhq55gp7qasqn77kshfykn9kqx0akzt7 --node https://api.s0.b.hmny.io --verbose` you'll see that `0x14` gets returned:
```
URL: https://api.s2.b.hmny.io, Response Body: {
  "jsonrpc": "2.0",
  "id": "3",
  "result": "0x14"
}
```

I did some quick digging around in go-sdk and the issue happens in [common.NewDecFromHex](https://github.com/harmony-one/go-sdk/blob/master/pkg/common/numeric.go#L53-L69) because of `half` is getting set to `0` (because `int((2 - 1) / 2) => 0`) and `front` subsequently being set to `""` - resulting in `f` being `nil`, e.g:
```
NewDecFromHex - i: 0x14
string.TrimPrefix - i: 14
len(i): 2
half: 0
front: 
back: 14
f: <nil>
b: 20
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x41db610]
```

Isn't `0x14` an invalid balance? Shouldn't it be way longer if it's a non-zero value?

I wasn't sure which repo to put this in since it's one hand a bug in go-sdk (the common.NewDecFromHex-function should deal with edge cases like this) but it also seems something has gotten messed up in the actual chain as well.

Let me know if an issue referencing this one should also be opened on harmony-one/harmony.

**Comment by mindstyle85** [comment]
I was able to reproduce it manually on devnet:

1. account balance on any shard should be 10k
2. send out a tx which leaves exactly 20 wei in balance: 
 ./hmy transfer --node="https://api.s0.os.hmny.io" --from one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --to one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --from-shard 1 --to-shard 0 --amount 9999.999978999999999980 --chain-id testnet

3. try to check balances:

./hmy --node="https://api.s0.os.hmny.io" balances one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x565b80]

goroutine 1 [running]:
math/big.(*Int).Mul(0xc0003dfae0, 0x0, 0xc00000e1c0, 0xc000747978)
	/home/edgar/.gimme/versions/go1.13.6.linux.amd64/src/math/big/int.go:168 +0xd0
github.com/harmony-one/harmony/numeric.NewDecFromBigIntWithPrec(0x0, 0x0, 0x2)
	/home/edgar/go/pkg/mod/github.com/harmony-one/harmony@v1.3.0/numeric/decimal.go:102 +0x70
github.com/harmony-one/harmony/numeric.NewDecFromBigInt(...)
	/home/edgar/go/pkg/mod/github.com/harmony-one/harmony@v1.3.0/numeric/decimal.go:95
github.com/harmony-one/go-sdk/pkg/common.NewDecFromHex(0xc0003879dc, 0x4, 0xd9ffa6)
	/home/edgar/go/src/github.com/harmony-one/go-sdk/pkg/common/numeric.go:67 +0x1ab
github.com/harmony-one/go-sdk/pkg/sharding.CheckAllShards(0x7ffcb90c1254, 0x19, 0x7ffcb90c1277, 0x2a, 0x0, 0xc0002ddc90, 0xc0002ddc20, 0x954ea4, 0xc0002fd040)
	/home/edgar/go/src/github.com/harmony-one/go-sdk/pkg/sharding/structure.go:60 +0x4c0
github.com/harmony-one/go-sdk/cmd/subcommands.init.0.func1(0xc00029e280, 0xc0002a85a0, 0x1, 0x2, 0x0, 0x0)
	/home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/balance.go:48 +0x6a6
github.com/spf13/cobra.(*Command).execute(0xc00029e280, 0xc0002a8540, 0x2, 0x2, 0xc00029e280, 0xc0002a8540)
	/home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1530e40, 0x1, 0xffffffffffffffff, 0x7)
	/home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/edgar/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
	/home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:112 +0x4d
main.main()
	/home/edgar/go/src/github.com/harmony-one/go-sdk/cmd/main.go:38 +0x163
