### ISSUE TITLE
Account Management Requirements

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/go-sdk#14]
**Account Management Requirements**
- [x] CLI Account Management Feature
- [x] Create Account
  - [x] Password Protect account
- [x] Import Private Key
- [x] Import Mnemonic
  - [x] Generate next account from mnemonic
- [x] Export Private Key
- [ ] Export Mnemonic
- [x] Account Balance

**Comment by Daniel-VDM** [comment]
Cannot export Mnemonic
