### ISSUE TITLE
ambiguous error in hmy

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/go-sdk#160]
./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --name mind2 --identity BBQ chicken wings --website mind2@harmony.one --security-contact mamapangaea --details "pink pony node runners2" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 10000 --bls-pubkeys 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12 --amount 1000 --chain-id testnet

commit: v300-d6ddd06, error: accepts 0 arg(s), received 2

so this is an error that is possible on every attribute if you dont use "", the problem is, from the error message itself, most people will not realise  this and wont know where the actual mistake is. Would be great if it can pinpoint the exact attribute where the error happened (--indentity in this case). Also isnt it that it accepts 1 args, but received 3? --identity arg1 arg2 arg3

**Comment by janet-harmony** [comment]
`--identity BBQ chicken wings` 
The CLI is reading "BBQ" as input to `--identity`, but not reading "chicken" or "wings", so there are 2 extra arguments.
This is a problem with the cobra library & will not be fixed before staking.
