### ISSUE TITLE
hmy edit validator throws wrong error(s)

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/go-sdk#167]
[ec2-user@ip-172-31-16-211 ~]$ ./hmy --node="https://api.s0.os.hmny.io" staking edit-validator --validator-addr one1hpyw7ezv566slfpna4y689rwx0qehdqlcfeag3 --active true
**[EditValidator] insufficient funds for gas * price + value -- 2020-03-08 21:11:44 +0000 UTC
[EditValidator] insufficient funds for gas * price + value -- 2020-03-08 21:11:59 +0000 UTC
[EditValidator] insufficient funds for gas * price + value -- 2020-03-08 21:17:48 +0000 UTC
[EditValidator] insufficient funds for gas * price + value -- 2020-03-08 21:21:32 +0000 UTC**
[EditValidator] staking validator does not exist -- 2020-03-08 23:57:13 +0000 UTC
commit: v304-0e26945, error: staking transaction error
check hmy cookbook for valid examples or try adding a --help flag

User has balance:
[ec2-user@ip-172-31-16-211 ~]$ ./hmy --node="https://api.s0.os.hmny.io/" balances one1hpyw7ezv566slfpna4y689rwx0qehdqlcfeag3
[
  {
    "shard": 0,
    "amount": 10000.000000000000000000
  },
  {
    "shard": 1,
    "amount": 0.000000000000000000
  },
  {
    "shard": 2,
    "amount": 0.000000000000000000
  },
  {
    "shard": 3,
    "amount": 0.000000000000000000
  }
]

Just the bolded parts shouldnt be there imo.

**Comment by Daniel-VDM** [comment]
This will be fixed when I implement a fix on the core protocol side to maintain error msgs better.
