### ISSUE TITLE
Make cookbook be a function of --chain-id given 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/go-sdk#174]
right now the cookbook is just a long string, but all the URLs are hardcoded to one of our networks. 

Make cookbook take into account --chain-id , so that pangaea is `os`, mainnet `t`, so on, so forth 

See this PR as motivation https://github.com/harmony-one/go-sdk/pull/173

**Comment by sophoah** [comment]
@Cem-Harmony @Daniel-VDM @janet-harmony @fxfactorial Guys, if that one is not urgent, I would like to work on this one. Thanks
