### ISSUE TITLE
[bug] hmycli crash using `--node=http://<ip address>:9500`

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/go-sdk#176]
![image](https://user-images.githubusercontent.com/4513927/76674765-056d1980-6570-11ea-871a-7248feed4e61.png)

Use domain name it works, like localhost, or api.s0.t.hmny.io, but IP address doesn't work.

**Comment by LeoHChen** [comment]
Try '127.0.0.1' also doesn't work.

**Comment by fxfactorial** [comment]
@Cem-Harmony implemented this feature
