### ISSUE TITLE
bad error message for a non existing validator

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/go-sdk#180]
./hmy --node=https://api.s0.os.hmny.io/ blockchain validator information one1leh5rmuclw5u68gw07d86kqxjd69zuny3h23c3

commit: v321-2c589a6, error: Catch all RPC error: not found address in current state one1leh5rmuclw5u68gw07d86kqxjd69zuny3h23c3: at root: 0xde5430365b80efb98d115e8d4ad6e5027eb85a4293d4949007a25afd32e574fd: address not present in state

**Comment by fxfactorial** [comment]
What’s a better error message you think ?

**Comment by mindstyle85** [comment]
This address does not exist (or has not been found) in the validator list -
something clean, without all those RPC errors and hashes

V V sre., 18. mar. 2020 ob 02:27 je oseba Edgar Aroutiounian <
notifications@github.com> napisala:
