### ISSUE TITLE
unnecessaries message appear when ran multi BLS key with key specified on blspass.txt

### ISSUE THREAD

**Issue by scraido** [harmony-one/go-sdk#186]
**Describe the bug**
Hi when i do create a multi same shard BLS with same passphrase and specified it on
root; $ blspass.txt

i got unnecessaries message after it show in what shard my node runs, it's worked but left unnecessaries message before, that make me doubt that my node is succeed run / not,,

it should not make people wonder, and type another command to checked that their node is run or not,

**To Reproduce**
1. Create 2 same BLS key with same passphrase
2. specified the passphrase on blspass.txt
3. run the node using;
$ ./node.sh -S -c -z -I -N staking -M -p blspass.txt

**Expected behavior**
It should after "shard 3" messages has been appear, the "couldn't find xxx using from blspass.txt" message should not appearing "again"

**Screenshots**
![bug-new](https://user-images.githubusercontent.com/44559893/76839415-0b147900-6868-11ea-97d0-f18b1d9caaaf.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
- Go environment:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build000170528=/tmp/go-build -gno-record-gcc-switches"

**Additional context**
the messages as you can see on the picture above was;
1st messages
couldn't find xxx using from blspass.txt

2nd messages
couldn't find xxx using from blspass.txt

3rd messages
assign to -> shard 3 (it should stop in here),,

but then the first and second messages is reproduce again, that's why i call it "unnecessaries message", because it's appear twice or appear again

4th message repeat the 1st messages
couldn't find xxx using from blspass.txt

5th message repeat the 2nd messages
couldn't find xxx using from blspass.txt

because it's appear twice, after "shard 3" messages appear, it could make people confuse that they node run or not, until they check using "latest-header" or
![bug-new2](https://user-images.githubusercontent.com/44559893/76840521-ecaf7d00-6869-11ea-861b-8b3b08daad36.png)

Thank you

**Comment by sophoah** [comment]
just adding the reference to https://github.com/harmony-one/staking-dashboard/issues/219 where @gupadhyaya was aware and to focus on the unnecessary messages appearing after the shard number.

Here is mine

```
node.sh: ############### Running Harmony Process ###############
[Multi-BLS] could not find passphrase for bls key file: 356b0732524bdd3a2ac6f2a09aa29da9a71b73167f42c64e5ba2b3322d82f79ade31b56efe61782f25c354c1dec28f88.key, using passphrase from stdin
[Multi-BLS] could not find passphrase for bls key file: 62937063063c3c8390c86fd406b3155158fe8ecf1e82b0116e1e27cd8fb021c61c39469658d212cb89168ada8ab89a08.key, using passphrase from stdin
[Multi-BLS] could not find passphrase for bls key file: 778fedb1699a7741eae03dbdcbc376c983b1a23aa9da2548c1706442acc3431747a957cf7aee2ae0fa028bc0c83a1684.key, using passphrase from stdin
[Multi-BLS] could not find passphrase for bls key file: dfca9b0bb41a358023b75136f51882e2b5396806f4287a0200f772c2b7b8a5981730fbc7558b086da8217969518d3498.key, using passphrase from stdin
Staking mode; node key 356b0732524bdd3a2ac6f2a09aa29da9a71b73167f42c64e5ba2b3322d82f79ade31b56efe61782f25c354c1dec28f8862937063063c3c8390c86fd406b3155158fe8ecf1e8
2b0116e1e27cd8fb021c61c39469658d212cb89168ada8ab89a08778fedb1699a7741eae03dbdcbc376c983b1a23aa9da2548c1706442acc3431747a957cf7aee2ae0fa028bc0c83a1684dfca9b0bb41a3
58023b75136f51882e2b5396806f4287a0200f772c2b7b8a5981730fbc7558b086da8217969518d3498 -> shard 0
```
the below are the continuation of the previous currently with the latest code ```version v5730-v1.3.5-39-ga429d020```
```
[Multi-BLS] could not find passphrase for bls key file: 356b0732524bdd3a2ac6f2a09aa29da9a71b73167f42c64e5ba2b3322d82f79ade31b56efe61782f25c354c1dec28f88.key, using passphrase from stdin
[Multi-BLS] could not find passphrase for bls key file: 62937063063c3c8390c86fd406b3155158fe8ecf1e82b0116e1e27cd8fb021c61c39469658d212cb89168ada8ab89a08.key, using passphrase from stdin
[Multi-BLS] could not find passphrase for bls key file: 778fedb1699a7741eae03dbdcbc376c983b1a23aa9da2548c1706442acc3431747a957cf7aee2ae0fa028bc0c83a1684.key, using passphrase from stdin
[Multi-BLS] could not find passphrase for bls key file: dfca9b0bb41a358023b75136f51882e2b5396806f4287a0200f772c2b7b8a5981730fbc7558b086da8217969518d3498.key, using passphrase from stdin
```
which is what OP is trying to highlight.

**Comment by C10NU7** [comment]
![IMG_20200323_175037_279](https://user-images.githubusercontent.com/37934859/77336202-dbfe7b80-6d2f-11ea-8914-70cba6e1a91d.jpg)

**Comment by gupadhyaya** [comment]
fixed in https://github.com/harmony-one/harmony/pull/2548 please confirm @scraido @mindstyle85 @C10NU7 @sophoah 
also close issue if fixed.

**Comment by mindstyle85** [comment]
this is confirmed fixed, so im closing the issue
