### ISSUE TITLE
Generate-BLS-Key to output shard number and/or input shard number and number of keys

### ISSUE THREAD

**Issue by michaelotis** [harmony-one/go-sdk#201]
It'd be helpful to add a helper to the generate-bls-key function to allow users to view what shard they're key is on, also to be able to specify what shard they want and how many keys to output instead of having to manually copy and paste into separate commands.

**Comment by fxfactorial** [comment]
Good idea, perhaps in meantime while controlling shard is possible, we can just have the cli keep generating for you until getting the right shard user wanted.
