### ISSUE TITLE
Unable to run hmy binary

### ISSUE THREAD

**Issue by saiSunkari19** [harmony-one/go-sdk#235]
**Describe the bug**
After install go-sdk, I used `./hmy` to run the binary. but it's not worked.

**To Reproduce**
```bash=
go get -u github.com/harmony-one/go-sdk
cd go-sdk
make
```
Then I run `./hmy`, following error occured.
`./hmy: error while loading shared libraries: libbls384_256.so: cannot open shared object file: No such file or directory`

**Expected behavior**
Able to run

**Environment**
OS: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux : 20.04
go-sdk Version (commit): `ec0a498945cb8564897cb2573db9dc5942bf73e7`

**Comment by Daniel-VDM** [comment]
Building the binary requires some upstream dependencies (as stated in the README). Please make sure you have all the dependencies from here: https://github.com/harmony-one/harmony/blob/master/README.md then try again.
