### ISSUE TITLE
Typo in help text of harmony binary

### ISSUE THREAD

**Issue by mellertson** [harmony-one/go-sdk#243]
In the help text for the command `$ ./harmony --help` the default port number for `--dns.port` should be 6000, but it is 9000.

In more detail if I do harmony --help among its output it reads...

```shell script
$ ./harmony --help

harmony is the Harmony node binary file
...
      --dns.port int                    port of customized dns node (default 9000)
      --dns.zone string                 use customized peers from the zone for state syncing
...
      --p2p.ip string                   ip to listen for p2p protocols (default "0.0.0.0")
      --p2p.keyfile string              the p2p key file of the harmony node (default "./.hmykey")
      --p2p.port int                    port to listen for p2p protocols (default 9000)
...
```

It looks like port 9000 is specified twice, which looks like a typo to me.  It seems like port 6000 is used for `--dns.port int` and port 9000 is used for `--p2p.port int`.

**Comment by LuttyYang** [comment]
Not feedback from this project, please move here: https://github.com/harmony-one/harmony
