### ISSUE TITLE
hmycli release using github action

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/go-sdk#245]
We need to implement a github action for the release of hmycli.

We'd release both mac, arm64, and amd64 versions of the hmycli and add it to the release build artifacts with the release tag pushed.

Please refer to the github action in the main repo.
https://github.com/harmony-one/harmony/blob/main/.github/workflows/ci.yaml

**Comment by jackyzhujiale** [comment]
@LeoHChen hi. I want to know where I can get the arm64 version hmycli binary? Thanks!
