### ISSUE TITLE
[feature] display staking and delegation information

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/go-sdk#249]
currently the account information won't display the staking and delegation details.  we need to display the account's delegation or staking info.

**Comment by LuttyYang** [comment]
It seems that there are two commands to view, What more detailed information is needed:

./hmy blockchain delegation by-validator --node="https://api.harmony.one/" [ONE address]

![image](https://user-images.githubusercontent.com/14296262/122774389-b6b63f80-d2db-11eb-8c7b-4724defa48d0.png)

./hmy blockchain delegation by-delegator --node="https://api.harmony.one/" [ONE address]

![image](https://user-images.githubusercontent.com/14296262/122774681-fd0b9e80-d2db-11eb-8ee5-fbb59d635b6e.png)

**Comment by LeoHChen** [comment]
seems we have already implemented those functions. closing the ticket.
