### ISSUE TITLE
Governance Voting in hmy CLI Turning Errors

### ISSUE THREAD

**Issue by hankthecrank4one** [harmony-one/go-sdk#266]
**Attempting:**
`./hmy --node=https://api.s0.t.hmny.io --space=staking-mainnet governance vote-proposal --proposal=QmPYGvNRkkn1Jf7Dvz7yP3FDLjXpkFDubMKiXvnwm1r6Vd --choice=Agree --key=wallet_name --passphrase`

**Returns error:**
`commit: v1-8561dc3, error: error: unauthorized, wrong version
`

**OS:** Ubuntu 20.04 (LTS) x64

**hmy version:**  Harmony (C) 2020. hmy, version v1-8561dc3 (runner@harmony.one 2021-07-19T14:05:24+0000)

**validator address:** one139wxucm2rl0aag8ej24r2rh0qk86dylvszxg5u

**More info:**  https://discord.com/channels/532383335348043777/552562703537799172/886451603740176426

**Comment by sophoah** [comment]
@LuttyYang @jhd2best

**Comment by LuttyYang** [comment]
@hankthecrank4one Can you use the v1.2.7 version to test if it works? Thanks!

**Comment by hankthecrank4one** [comment]
Sorry with it so close to the deadline I just used the voting website.  However, others in telegram have reported it working now.

**Comment by LuttyYang** [comment]
ok, closed, thanks
