### ISSUE TITLE
arm64 macos 

### ISSUE THREAD

**Issue by cylim** [harmony-one/go-sdk#271]
While I am working on the homebrew formula, it failed the CI/CD test for arm64 Mac device, unfortunately I don't have a M1 Macbook to debug the issue.

I found out that the arm64 build is removed from go-sdk repo, is there any identified issues that I can help?

https://github.com/harmony-one/go-sdk/compare/v1.2.6...v1.2.7

**Comment by cylim** [comment]
It seems like the issue is related to openssl.

**Comment by LuttyYang** [comment]
@cylim  currently not support arm64 Mac devices, It needs some problem solving

I tested in Mac device(with M1).I tried to solve the problems related to openssl, but there are some other internal dependencies that still do not support the arm64 system.

![image](https://user-images.githubusercontent.com/14296262/135743596-ce69f1ef-1425-4763-bc58-1a392bd81254.png)

**Comment by LeoHChen** [comment]
I think we can skip arm64 macos support for now.

**Comment by LuttyYang** [comment]
@LeoHChen @cylim Ok, closed currently.

**Comment by cylim** [comment]
Unfortunately I can't help with this. My friend is able to run on arm64 Macbook, his openssl is on rosetta(intel) version.
I will ask Homebrew team whether it is possible to use rosetta openssl as dependencies for the formula. Thanks :D
