### ISSUE TITLE
Transactions underpriced when trying to send batch transactions with JSON file

### ISSUE THREAD

**Issue by MurphValidator** [harmony-one/go-sdk#282]
Since July i've been sending batch transactions (30-40 transactions) using:

./hmy --node="https://api.s0.t.hmny.io" transfer --file /mnt/c/jsonfiles/weeklyrewards.json

Since the implementation of the 30 gwei gas price, I tried using:

./hmy --node="https://api.s0.t.hmny.io" transfer --file /mnt/c/jsonfiles/weeklyrewards.json \
    --gas-price 30

and the output:
[
  {
    "transaction-hash": "0xa9118620a12e95c994c04817a5805a1ca8ef6e75feb2298527dbb1c9d5bf15ab",
    "errors": [
      "[2022-01-17 02:55:41.951225] [Plain transaction] transaction gas-price is 1.000000000000000062 ONE; minimum gas price is 30.000000000000001868 ONE: transaction underpriced -- 2022-01-16 20:55:31 -0600 CST",
      "[2022-01-17 02:55:41.951228] error found for transaction hash: 0xa9118620a12e95c994c04817a5805a1ca8ef6e75feb2298527dbb1c9d5bf15ab",
      "[2022-01-17 02:55:41.951229] Failed to confirm transaction"
    ],
    "time-signed-utc": "2022-01-17 02:55:32.587103"
  }
]

**Comment by jhd2best** [comment]
please use the latest version. thanks. https://github.com/harmony-one/go-sdk/releases/tag/v1.2.9

**Comment by MurphValidator** [comment]
Tried it again after downloading new version and it worked perfect. Thank you!

**Comment by MurphValidator** [comment]
I ran it again, minus the first 4 transactions, and the rest went through no problem.
