### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by sophoah** [harmony-one/go-sdk#42]
Describe the issue : 
Segfault error

How to replicate:
On a ubuntu aws free tier machine, 
curl -LO https://harmony.one/hmycli && chmod +x hmycli && mv hmycli hmy
./hmy --node="https://api.s1.b.hmny.io/" balances one1yc06ghr2p8xnl2380kpfayweguuhxdtupkhqzw

Full error message below:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fac45b12448]

runtime stack:
runtime.throw(0xd71ab8, 0x2a)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 22 [syscall]:
runtime.cgocall(0xa16a15, 0xc000218de0, 0xc000010240)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000218db0 sp=0xc000218d78 pc=0x40777b
net._C2func_getaddrinfo(0xc0003f8a00, 0x0, 0xc000354bd0, 0xc000010240, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:91 +0x55 fp=0xc000218de0 sp=0xc000218db0 pc=0x5866e5
net.cgoLookupIPCNAME.func1(0xc0003f8a00, 0x11, 0x11, 0xc000354bd0, 0xc000010240, 0x10, 0x4305af, 0x8)
        /usr/local/go/src/net/cgo_unix.go:154 +0x13e fp=0xc000218e28 sp=0xc000218de0 pc=0x58bf1e
net.cgoLookupIPCNAME(0xd3837b, 0x2, 0xc0003f8980, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:154 +0x176 fp=0xc000218f18 sp=0xc000218e28 pc=0x587bb6
net.cgoIPLookup(0xc000755560, 0xd3837b, 0x2, 0xc0003f8980, 0x10)
        /usr/local/go/src/net/cgo_unix.go:206 +0x67 fp=0xc000218fb8 sp=0xc000218f18 pc=0x5882a7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000218fc0 sp=0xc000218fb8 pc=0x45e681
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:216 +0xc7

goroutine 1 [select]:
net.(*Resolver).lookupIPAddr(0x15b8760, 0x1011260, 0xc00002a0a0, 0xd3837b, 0x2, 0xc0003f8980, 0x10, 0x7fac4a89f008, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup.go:275 +0x663
net.(*Resolver).LookupIPAddr(...)
        /usr/local/go/src/net/lookup.go:205
net.LookupIP(0xc0003f8980, 0x10, 0x1bb, 0x0, 0x0, 0x3, 0x0)
        /usr/local/go/src/net/lookup.go:191 +0x88
github.com/valyala/fasthttp.resolveTCPAddrs(0xc0003f8980, 0x14, 0xc0003f8900, 0x14, 0x15f6bc0, 0x8, 0x203000, 0xc000354b40)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:425 +0xc7
github.com/valyala/fasthttp.(*TCPDialer).getTCPAddrs(0x15201c0, 0xc0003f8980, 0x14, 0xc000731500, 0xc0007315a0, 0x40ff29, 0xc00034be10, 0x4e8559, 0xc0003f8980, 0x14)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:390 +0x14c
github.com/valyala/fasthttp.(*TCPDialer).dial(0x15201c0, 0xc0003f8980, 0x14, 0xe30000000070f000, 0xb2d05e00, 0xe3043d6c2a5a5d6f, 0xc0003f8980, 0x10, 0xc000354b70)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:255 +0xac
github.com/valyala/fasthttp.(*TCPDialer).Dial(...)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:164
github.com/valyala/fasthttp.Dial(0xc0003f8980, 0x14, 0xc000354b01, 0xc0003f8980, 0x14, 0xc00034be98)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:36 +0x51
github.com/valyala/fasthttp.dialAddr(0xc0003f8980, 0x14, 0x0, 0xc000160100, 0xc00016c300, 0xcd4cec95, 0x15b8f80, 0xc0003f8920, 0xc0004915f0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1566 +0x4a
github.com/valyala/fasthttp.(*HostClient).dialHostHard(0xc0000c4f00, 0xf15118, 0xc0000c4f00, 0x73454f, 0xc00008fb00)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1526 +0x199
github.com/valyala/fasthttp.(*HostClient).acquireConn(0xc0000c4f00, 0x1a7c7ca7, 0x15b8f80, 0x20)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1292 +0xee
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc0000c4f00, 0xc0000c6dc0, 0xc00008fb00, 0x0, 0x10, 0xc000491600)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1143 +0xcb
github.com/valyala/fasthttp.(*HostClient).do(0xc0000c4f00, 0xc0000c6dc0, 0xc00008fb00, 0x780000c0003f8980, 0xc0007318a0, 0x78017356b33546da)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1110 +0x57
github.com/valyala/fasthttp.(*HostClient).Do(0xc0000c4f00, 0xc0000c6dc0, 0xc00008fb00, 0x10, 0xc000235d00)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1060 +0x76
github.com/valyala/fasthttp.(*Client).Do(0x15b9460, 0xc0000c6dc0, 0xc00008fb00, 0xc000731a20, 0x18)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:437 +0x1f2
github.com/valyala/fasthttp.Do(...)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:37
github.com/harmony-one/go-sdk/pkg/rpc.baseRequest(0xd3e14c, 0xe, 0xc0003f8800, 0x18, 0xc44a20, 0xc0004ce020, 0x13c, 0x13c, 0xc000731b80, 0x40ddcd, ...)
        /go/src/github.com/harmony-one/go-sdk/pkg/rpc/query.go:32 +0x48a
github.com/harmony-one/go-sdk/pkg/rpc.Request(0xd3e14c, 0xe, 0xc0003f8800, 0x18, 0xc44a20, 0xc0004ce020, 0x0, 0x93530b, 0xc7aea0)
        /go/src/github.com/harmony-one/go-sdk/pkg/rpc/query.go:59 +0xab
github.com/harmony-one/go-sdk/pkg/sharding.CheckAllShards(0x7ffd8325e777, 0x19, 0x7ffd8325e79a, 0x2a, 0xd39300, 0x4, 0x981df0, 0xc0002a3d48, 0xc0002a3d18)
        /go/src/github.com/harmony-one/go-sdk/pkg/sharding/structure.go:43 +0x224
github.com/harmony-one/go-sdk/cmd/subcommands.init.0.func1(0xc000266280, 0xc000278940, 0x1, 0x2, 0x0, 0x0)
        /go/src/github.com/harmony-one/go-sdk/cmd/subcommands/balance.go:17 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000266280, 0xc0002788e0, 0x2, 0x2, 0xc000266280, 0xc0002788e0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x1527780, 0xd36180, 0x0, 0xc0002ae500)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/harmony-one/go-sdk/cmd/subcommands.Execute()
        /go/src/github.com/harmony-one/go-sdk/cmd/subcommands/root.go:87 +0x2e
main.main()
        /go/src/github.com/harmony-one/go-sdk/cmd/main.go:32 +0xbe

goroutine 5 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.init.0.func1()
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/header.go:1443 +0x2a
created by github.com/valyala/fasthttp.init.0
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/header.go:1441 +0x3a

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc000064780, 0xc0000646c0)
        /go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0xdd

goroutine 9 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc000064780, 0xc000064720)
        /go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
        /go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:30 +0x109

goroutine 10 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000252450)
        /go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /go/pkg/mod/github.com/ethereum/go-ethereum@v1.8.27/core/tx_cacher.go:55 +0x9f

goroutine 11 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc000252710)
        /go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191029195210-b3eeed6b4152/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
        /go/pkg/mod/github.com/harmony-one/harmony@v0.0.0-20191029195210-b3eeed6b4152/core/tx_cacher.go:55 +0x9f

goroutine 12 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*Client).mCleaner(0x15b9460, 0xc000263b00)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:462 +0x143
created by github.com/valyala/fasthttp.(*Client).Do
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:434 +0x24b

goroutine 13 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*HostClient).connsCleaner(0xc0000c5540)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1354 +0x332
created by github.com/valyala/fasthttp.(*HostClient).acquireConn
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1289 +0x192

goroutine 14 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/valyala/fasthttp.(*TCPDialer).tcpAddrsClean(0x15201c0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:367 +0x110
created by github.com/valyala/fasthttp.(*TCPDialer).dial.func1
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/tcpdialer.go:252 +0x6a

goroutine 20 [runnable]:
github.com/valyala/fasthttp.(*HostClient).connsCleaner(0xc0000c4f00)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1302
created by github.com/valyala/fasthttp.(*HostClient).acquireConn
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/client.go:1289 +0x192

goroutine 21 [select]:
net.cgoLookupIP(0x1011220, 0xc00057b140, 0xd3837b, 0x2, 0xc0003f8980, 0x10, 0x200, 0x202, 0x5, 0x1, ...)
        /usr/local/go/src/net/cgo_unix.go:217 +0x195
net.(*Resolver).lookupIP(0x15b8760, 0x1011220, 0xc00057b140, 0xd3837b, 0x2, 0xc0003f8980, 0x10, 0x0, 0x0, 0xc00016c480, ...)
        /usr/local/go/src/net/lookup_unix.go:96 +0x1a4
net.glob..func1(0x1011220, 0xc00057b140, 0xc0003af2f0, 0xd3837b, 0x2, 0xc0003f8980, 0x10, 0x0, 0xefd1e705c, 0x0, ...)
        /usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:269 +0x116
internal/singleflight.(*Group).doCall(0x15b8770, 0xc00034d400, 0xc0003f89c0, 0x13, 0xc00057b180)
        /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x29d

**Comment by LeoHChen** [comment]
@sophoah , what's the instance type are you running ?  t2.micro?  I run it on my ubuntu t3.micro instance, and it works fine. Also, what's the version of the hmycli?  Please use ```./hmy  version```

I am running on ubuntu.
```
ubuntu@ip-172-31-22-62:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by LeoHChen** [comment]
```
curl http://169.254.169.254/latest/meta-data/instance-type
t3.micro
```

**Comment by sophoah** [comment]
@LeoHChen : 
ubuntu@ip-x.x.x.x:~/hmy$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
ubuntu@ip-x.x.x.x:~/hmy$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by sophoah** [comment]
./hmy version
Harmony (C) 2019. hmy, version v119-926047d (@harmony.one 2019-11-04T21:57:29+0000)

**Comment by sophoah** [comment]
and yes this is a t2.micro (free aws tier)

**Comment by sophoah** [comment]
ubuntu@ip-x.x.x.x:~/hmy$ uname -a
Linux ip-172-31-12-193 4.15.0-1050-aws #52-Ubuntu SMP Thu Sep 12 19:56:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-x.x.x.x:~/hmy$ uname -m
x86_64

**Comment by fxfactorial** [comment]
Another example of this, but in the main harmony repo: https://pastebin.com/1X4ntWeU

**Comment by LeoHChen** [comment]
@sophoah , please try another instance like t3.micro, not t2.micro.  Thanks.

**Comment by sophoah** [comment]
@LeoHChen  t2.micro definitely worked I just tested. The difference is the OS version, i used a ubuntu 16.x so definitely that issue is the same as the other one I discovered when trying to build a new external instance. If you ok i can close this issue since it is linked to the one @SebastianJ opened : https://github.com/harmony-one/harmony/issues/1811

**Comment by fxfactorial** [comment]
@sophoah fixed but please check
