### ISSUE TITLE
Encoding error when creating a validator

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/go-sdk#46]
Command:
```
./hmy staking create-validator --amount 1 --bls-pubkeys 0x678ec9670899bf6af85b877058bea4fc1301a5a3a376987e826e3ca150b80e3eaadffedad0fedfa111576fa76ded980c 0xe111e3e705067203d3416c102ed54f6ed33c2a0aec24562dba3b13d209cf3a18 --identity foo --details bar --max-change-rate 10 --max-rate 10 --max-total-delegation 10 --min-self-delegation 10 --name baz --rate 10 --security-contact jim --validator-addr one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --website lol.com --passphrase=''
```

Error:
```
Error: encoding/hex: invalid byte: U+0078 'x'
```

**Comment by coolcottontail** [comment]
1)The command is createvalidator, not create-validator.
2)If there are more than one BLS key,  please use "," to separate public bls keys. 
3)Please remove 0x and use the bls hex bytes directory.
4)It seems e111e3e705067203d3416c102ed54f6ed33c2a0aec24562dba3b13d209cf3a18 is not a valid BLS public key. where did you get this key value?

Can you try the following ? 

./hmy staking createvalidator  --amount 1 --bls-pubkeys  678ec9670899bf6af85b877058bea4fc1301a5a3a376987e826e3ca150b80e3eaadffedad0fedfa111576fa76ded980c,5eb1eec590b2a763da7454b49c13e331b41816853d1b70a7868989dbdf63b450339983cd3020c974f4fc23e2a4475116   --identity foo --details bar --max-change-rate 10 --max-rate 10 --max-total-delegation 10 --min-self-delegation 10 --name baz --rate 10 --security-contact jim --validator-addr one103q7qe5t2505lypvltkqtddaef5tzfxwsse4z7 --website lol.com --passphrase=''

**Comment by Daniel-VDM** [comment]
e111e3e705067203d3416c102ed54f6ed33c2a0aec24562dba3b13d209cf3a18 must have been the private key i copied and pasted. 

We should update the cookbook.
