### ISSUE TITLE
Give precedence to IP input over host URL when given to --node

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/go-sdk#81]

**Comment by janet-harmony** [comment]
Elaborate?

**Comment by fxfactorial** [comment]
When we use —node with a url like pga.pangaea for balances , we use it for a call to sharding structure. And then use those results to check balances across all shards. But if we should update logic to not do the initial call to sharding structure if the node input is an ip address because here user is showing intent to target a particular machine
