### ISSUE TITLE
HMY edit-validator ask for Absolute Path

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/go-sdk#96]
Trying to edit my validator on devnet by running the command bellow:

`./hmy staking edit-validator --validator-addr one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec --name Yelllowsin --identity Yelllowsin --website yelllowsin@harmony.one --security-contact Yellowsin --details "Maha Lakshmi" --rate 0.3 --min-self-delegation 2 --max-total-delegation 11000 --remove-bls-key 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e --add-bls-key 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e --chain-id devnet`

HMY returns with this error:

```
For bls public key: 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e
Enter the absolute path to the encrypted bls private key file:

Error: keypath is not absolute path
v179f4cf946: keypath is not absolute path
```

I am sure i am passing the correct BLS KEY parameter as this same parameter works for "create-validator" as shown bellow:

`./hmy staking create-validator --validator-addr one1echapu535qgtc5ktkgjj3raec4x4gp0a2mh9ec --name Yelllowsin --identity yelllowsin --website yelllowsin@harmony.one --security-contact Yelllowsin --details "Maha Lakshmi" --rate 0.3 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 2 --max-total-delegation 11000 --amount 1000 --bls-pubkeys 0xa8a0637c7e11e2ea82c23ec1c0dcae3963a34bbabd92b03f9d895d04377ac72ae770da75c4c5868490378501cbd3888e --chain-id devnet`

**Comment by gupadhyaya** [comment]
@yelllowsin I am unable to reproduce the issue. It works for me fine. Can you pull the latest hmy binary and check if the problem exists? Thanks.

**Comment by yelllowsin** [comment]
@gupadhyaya tested all over again without 0x in front of the BLS and it worked. I got a bit confused, because somehow it works on create-validator using 0x in front of the BLS key (i guess there might be some sanitazination on the code that removes the 0x) and on edit-validator it doesn't work, you have to remove the 0x.

The whole confusion came from this command:

./hmy keys generate-bls-key matrix
Enter passphrase:
Repeat the passphrase:
{
  "public-key": "0x44d8e9b3da3d39b9c22c3981dba7fa64055d1c7620fa289509027ecd0f4c919ed6024d9296bc987d088ae978bb241d14",
  "private-key": "0xefe0cea183aa3f9165641d02f689668e742e3740aecb0bca48cd2ebcd6980000",
  "encrypted-private-key-path": "/home/harmony_one1q56/44d8e9b3da3d39b9c22c3981dba7fa64055d1c7620fa289509027ecd0f4c919ed6024d9296bc987d088ae978bb241d14.key"
}

You can clearly see that the public key starts with 0x, thus i thought that would be the public-key to be used as a parameter.

Well, i guess you can close the issue, it just needs to be clear for the users that you should not use the BLS key as parameter with the 0x in front of it, because i am sure some will make the same confusion i did.

**Comment by gupadhyaya** [comment]
@yelllowsin Thanks for redoing the test. We will fix the generate-bus-key to not add '0x' for the public-key and private-key parts.
